### ISSUE TITLE
Criação da Arquitetura do Sistema

### ISSUE THREAD

**Issue by wesleey** [teampi2/projeto#5]
- Pablo Kauan Martins Timbó

**Comment by PabloKauan-TI** [comment]
[Padrão Arquitetural - BotEdu.pdf](https://github.com/user-attachments/files/18191753/Padrao.Arquitetural.-.BotEdu.pdf)
[EduBot.pdf](https://github.com/user-attachments/files/18191848/EduBot.pdf)
